# Use root/example as user/password credentials
# Requires docker and docker compose.
#   sudo apt install docker docker-compose
# Create a .env and add values for INIT and ADM user/password
# To launch run:
#   sudo docker-compose -f .mongodb-compose.yml up

version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $INIT_USR
      MONGO_INITDB_ROOT_PASSWORD: $INIT_PWD

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $ADM_USR
      ME_CONFIG_MONGODB_ADMINPASSWORD: $ADM_PWD
